language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
  - "pypy3"
matrix:
  include:
    # add a pep8 test
    - python: 3.5
      env: TOXENV=pep8
    # add a test of setup.py using python 3.5
    - python: 3.5
      env: TOXENV=setup35
    # add a test of setup.py using python 3.4
    - python: 3.4
      env: TOXENV=setup34
    # add a test of setup.py using python 3.3
    - python: 3.3
      env: TOXENV=setup33
    # add a setup.py test using python 2.7
    - python: 2.7
      env: TOXENV=setup27
  allow_failures:
    - env: TOXENV=pep8
    - python: "pypy"
    - python: "pypy3"
# install requirements
install:
  # make sure libffi-dev, gnupg2, and pgpdump are installed
  - sudo apt-get update
  - sudo apt-get install -y libffi-dev gnupg2 pgpdump
  # ensure tox and coveralls are installed
  - pip install tox python-coveralls
# set TOXENV if it isn't yet
before_script:
  - if [[ -z "$TOXENV" ]]; then export TOXENV=py${TRAVIS_PYTHON_VERSION//.}; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 'pypy' ]]; then export TOXENV=pypy; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 'pypy3' ]]; then export TOXENV=pypy3; fi
# run tox
script:
  - ./tox.sh
# and report coverage to coveralls, but only if this was a pytest run
after_success:
  - if [[ "${TOXENV}" == "py"* ]]; then coveralls; fi
